### PR TITLE
Create quiet.js [wip, help wanted!]

### PR DESCRIPTION
**Pull request by jywarren**
Creating a behavior which auto-quiets everyone in our chatroom, except for hostmask-based exceptions we've created. 

We'll also add a way to notify all users that may not be exempted, how to request an exemption. Perhaps in the Welcome behavior. This could be a link to an email address, or a form, or something else. 

Or, we could have a send/response behavior with `plotsbot` itself to become unquieted?

@icarito @ryzokuken @pdurbin ... what do you think?

We've already exempted all Riot/Matrix users from this ban based on host mask.

### CODE REVIEW

**Comment by jywarren** [comment]
Oh and sorry, this is due to abusive bot content repeatedly being posted in our IRC channel.

**Comment by ryzokuken** [comment]
@jywarren this looks incomplete?

**Comment by jywarren** [comment]
Yeah, sorry, i don't have time at the moment to keep working on it! If it seems easy to finish off, i'd appreciate the help!

**Comment by pdurbin** [comment]
If OFTC is becoming too spammy, you could ask IRC users to switch to the Gitter IRC gateway. I'm not sure what that would mean for plotsbot though.

**Comment by jywarren** [comment]
hi @icarito @ryzokuken i'd like to turn plotsbot back on after merging this, which will auto-quiet all direct IRC chat joiners (but not Matrix/Riot/Gitter -- exempted here, and not our publiclab.org/chat IRC joiners, who we've exempted in IRC settings), but plotsbot will need op privileges once this is enabled.

**Pull request merged**
