### PR TITLE
Reorder and revamp action parameters for consistency

### PR DESCRIPTION
**Pull request by ryzokuken**
Fixes: https://github.com/publiclab/plotsbot/issues/106

cc @jywarren

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good to me, @ryzokuken !! CodeClimate doesn't seem to like it though :-P

**Comment by ryzokuken** [comment]
@jywarren it doesn't! That's because we're passing 5 arguments to a function. Perhaps we could solve that another day? Feel free to merge this if you're okay with this change. This is perhaps the only blocking part after which I could implement the memory-based behavior with relative ease.

**Comment by jywarren** [comment]
I'm ok with it, go ahead and merge! Thank you! When i get too many
parameters, i pass an options block. But I don't know the "best" way to do
this.

**Comment by ryzokuken** [comment]
`options` def. sounds good. Could you make an issue for it? If you don't have the time, let me know and I will.

**Comment by ryzokuken** [comment]
Merging this.

**Pull request merged**
