### PR TITLE
Remove unnecessary environments and add Jasmine environment

### PR DESCRIPTION
**Pull request by ryzokuken**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@ananyo2012 I will make sure it is before merging.

**Comment by ananyo2012** [comment]
:+1:

**Comment by ryzokuken** [comment]
@ananyo2012 I rebased it now. If it's okay with you, I will merge this as soon as the checks finish.

**Comment by ryzokuken** [comment]
@ananyo2012 Done.

**Pull request merged**
