### PR TITLE
Make a Dockerfile and add a .dockerignore

### PR DESCRIPTION
**Pull request by ryzokuken**
@icarito @jywarren take a look at this.

### CODE REVIEW

**Comment by jywarren** [comment]
Cool -- what does this change about the Docker setup? How was yarn working before? 

Just catching up after the Barnraising, thanks!!!

**Comment by ryzokuken** [comment]
@jywarren We didn't have a Dockerfile before, which didn't allow us to containerize the bot and utilize Jenkins. Awaiting @icarito's further instructions.

**Comment by icarito** [comment]
Please merge this so we can test from master? Or pick a branch for production (we use `stable` for `plots`).
Thanks and sorry for the delay!

**Comment by ryzokuken** [comment]
No worries, Sebastian!

I'm fine with using an alternate branch for production code, but we might as well keep `master` for the same purpose (at least for the time being, when our `master` isn't exactly cluttered with new code everyday).

**Comment by ryzokuken** [comment]
Merging this!

**Pull request merged**
