### PR TITLE
Added a "build passing" badge to README

### PR DESCRIPTION
**Pull request by Alhern**
Added the TravisCI badge below the header and above the project description in README.

### CODE REVIEW

**Comment by ryzokuken** [comment]
Wow @Alhern, that was quick! This looks awesome, I am merging it.  
Thanks for your contribution. Feel free to hang around and please take a look at our other issues, especially the ones labelled [`fto-candiate`](https://github.com/publiclab/plotsbot/issues?q=is%3Aopen+is%3Aissue+label%3Afto-candidate). These issues are a nice step-up from the issue you just solved, and some of them might interest you.

@jywarren notice how Github acknowledges the fact that @Alhern is a first time contributor.

**Comment by ryzokuken** [comment]
@Alhern also, I would like to point out, that it would be much easier for you if you make a separate branch for each PR, and keep your `master` branch clean. For more information and why it is both important and useful at the same time, read [this](https://gist.github.com/Chaser324/ce0505fbed06b947d962#create-a-branch).

**Comment by Alhern** [comment]
Thank you so much. I'm still learning but I will make sure to look around and try to help whenever I can.

**Comment by ryzokuken** [comment]
@Alhern you're doing great.  
See, you're a contributor already.

**Comment by ananyo2012** [comment]
Wow great! Congrats @Alhern for your first PR! Great co ordination @ryzokuken

**Comment by jywarren** [comment]
Agreed, great! Thanks all!

**Pull request merged**
