### PR TITLE
David and devDependencies (resolves #84)

### LINKED ISSUE #84: Add David's devDependencies badge on README and subsequently upgrade them
Now that we're working on upgrading the `github` package in our dependencies, it would be important for us to keep a track of our devDependencies as well and upgrade them whenever a new stable release surfaces. (For now, both `coveralls` and `eslint` are outdated)

### PR DESCRIPTION
**Pull request by ryzokuken**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren coveralls and eslint need to be updated. I don't know if there are any breaking changes (there totally could be, these are major version bumps), but let me try.

**Comment by ryzokuken** [comment]
@jywarren tests passed locally, but we'll have to see if coverage reporting works fine I guess.

**Comment by ryzokuken** [comment]
@jywarren okay, it seems things do work. Look into this and let me know if it's okay from your side to merge this.

**Comment by jywarren** [comment]
Cool, looks great!

**Comment by ryzokuken** [comment]
@jywarren Okay then, merging this.

**Pull request merged**
