### PR TITLE
Initial Release

### PR DESCRIPTION
**Pull request by ryzokuken**
Made an intial 0.1.0 release for plotsbot. This is the same version which is currently deployed to #publiclab-testing. 

@jywarren Please look into this and merge if you find it okay. The most substantial changes (and the ones I'd definitely like you to take a look at) are in the README.

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Maybe I should also ask contributors to name branches appropriately? Eg: `minor-${issue-number}` or `patch-${issue-number}`? Or does it sound like too much work? What about naming commit messages appropriately?

**Comment by jywarren** [comment]
@publiclab/soc - take a look if you have a chance -- thanks!

**Comment by jywarren** [comment]
Looking good! Do you have thoughts on testing? I think you could in theory turn your scenario "dialogues" into a test suite for the bot -- see how this project uses a "narrative" to actually test out the game in a fun way? https://github.com/jywarren/pxlqst#test-adventure

That'd make the test suite almost like easy-to-follow documentation of the bot's features, even for non-coders, you know?

**Comment by jywarren** [comment]
Although to be clear, you could develop this in a separate PR :-) one thing at a time!

**Comment by ryzokuken** [comment]
@jywarren great, thanks!

Yes, testing is indeed an important part. I will look into a few JS testing frameworks and come back to the community to choose the most appropriate one.

Edit: Woah, that game looks awesome. Will look into Jasmine.

**Comment by jywarren** [comment]
tape is a bit simpler of a test framework -- see the WebJack test library
for an example! But Jasmine has lots of awesome features for web-based
testing, so it's also an option. But a bit heavier.

**Comment by ryzokuken** [comment]
@jywarren tomorrow, I will look into testing and linting. Thanks.

**Comment by ananyo2012** [comment]
Wow this looks great! NVM is new to me. Eager to test it in development. The concept of bot development is new to me. But will learn along with this. And yes we should have a good tests written right from the start. I am familiar with Jasmine but feel free to decide what will be most suited for this project.

**Comment by jywarren** [comment]
Hey, this looks ready to merge. @ryzokuken why don't you go ahead and open up a separate issue for testing. It sounds like @aspriya is also interested in choosing a test framework (and may go with Jasmine as his work will be browser-based) but keep a line of communication open as you figure out how testing will work!

**Comment by jywarren** [comment]
Oh, and @ryzokuken you should go ahead and merge this once you've created a new issue for tests. PRs should be separate and modular :-) great work!

**Pull request merged**
