### PR TITLE
Switch to a promise based workflow

### PR DESCRIPTION
**Pull request by ryzokuken**
As of now, we had just one message-triggered behavior (help) which would return things instantly. Now that we are getting into making calling APIs and making database calls and whatnot, things will start taking more time. Blocking the entire bot's functioning during this process will make it struggle to work in real-life scenarios. Thus, we should use a promise based workflow. Notice here that we wrapped `Promises` around each function call to ensure that we the behavior can return their a value or a promise that resolves to a value and there will no difference using either.

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren @ananyo2012 what about this one?

**Comment by ananyo2012** [comment]
Can we have something if the Promise fails like in a `.catch` block ?

**Comment by ryzokuken** [comment]
@ananyo2012 is this enough?

**Comment by ananyo2012** [comment]
LGTM. To be frank I am not good at Promises. Let's merge this one and we
can improve it if needed.

**Pull request merged**
