### PR TITLE
Added docker-compose file. Expose to localhost:4001.

### PR DESCRIPTION
**Pull request by icarito**
Now I'll setup jenkins to auto-deploy master branch.

### CODE REVIEW

**Comment by jywarren** [comment]
Cool! How does this look, then?

**Comment by ryzokuken** [comment]
@jywarren @icarito It looks awesome! Should I merge this already?

**Comment by icarito** [comment]
Yes please merge and let's see it autodeploy! It is accessible only to `localhost:4001` on tycho. Tweak as you prefer in `docker-compose.yml`. Thank you!

**Comment by ryzokuken** [comment]
Great! Merging this. I'd need to look up some docs to be able to sensibly make changes to the `docker-compose.yml`, let me just look it up.

Thanks, Sebastian.

**Comment by icarito** [comment]
Actually it's quite simple, just look wher it says 4001 is the port. You need to set this up to trigger the jenkins build, let me look it up for you.

**Comment by ryzokuken** [comment]
By the way, it worked perfectly (https://riot.im/app/#/room/#publiclab-testing:matrix.org).

**Comment by icarito** [comment]
Please check `settings` `integrations / services` and Jenkins (Github plugin). The hook url is https://jenkins.laboratoriopublico.org/github-webhook/

**Comment by icarito** [comment]
image

**Comment by ryzokuken** [comment]
looks good? screen shot 2018-02-02 at 10 55 19 am

**Comment by ryzokuken** [comment]
Tested, it works.

**Comment by icarito** [comment]
Looking at logs, fixing permissions and rebuilding...

**Comment by icarito** [comment]
Okay this time it built the container and deployed https://jenkins.laboratoriopublico.org/job/Plotsbot/5/console

**Comment by ryzokuken** [comment]
Great! It also showed up in the chatroom.

**Pull request merged**
