### PR TITLE
Use jasmine instead of jasmine-node for testing

### PR DESCRIPTION
**Pull request by ryzokuken**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@ananyo2012 This one any better?

**Comment by ananyo2012** [comment]
You can go on with the tests now.

**Comment by ryzokuken** [comment]
@ananyo2012 Wanted to discuss a few things about the tests. Ping me whenever you are free for a few minutes.

**Comment by ananyo2012** [comment]
Just checking up with all the new issues.

**Comment by jywarren** [comment]
Great teamwork, you two! 🎈

**Pull request merged**
