### PR TITLE
Add a utility function for executing scripts

### PR DESCRIPTION
**Pull request by ryzokuken**
@icarito looks good? Let's export this next and use it in a sample behavior. Perhaps something chatops101 style. What do you say?

### CODE REVIEW

**Comment by icarito** [comment]
This looks in accordance with our discussion, looking forward to seeing this in action, how to hook it up with a behaviour and trigger it? :-)

**Comment by ryzokuken** [comment]
@icarito we would probably just need to call this function inside a behavior to execute a shell command, hence I added it to `utils`. Which simple behavior could we test this on?

**Comment by icarito** [comment]
Please automate the command `hddtemp /dev/sd?` - don't concern yourself with shell expansion, we can run it like `bash -c "hddtemp /dev/sd?"`. This should be triggered when we ask plotsbot how hot it is :sun_with_face:

**Comment by ryzokuken** [comment]
@jywarren Let's ignore the coverage warning for now. Coverage for this function will be improved in #67 anyway.

**Comment by ananyo2012** [comment]
https://github.com/publiclab/plotsbot/pull/67 already contains this change. Should I review that and close this one?

**Comment by ryzokuken** [comment]
@ananyo2012 #67 was based on this branch. Let's merge this when we're ready, I will bump the project version, rebase #67 on the tag commit and update, then we merge that one and I would bump up the version again.

What do you say? 😛

**Comment by ananyo2012** [comment]
Great! Sounds perfect. Perhaps you can write a test for the behavior in your next PR that would increase the coverage too.

**Comment by ananyo2012** [comment]
Merged!

**Pull request merged**
