### PR TITLE
Add support for fallback message behaviors

### PR DESCRIPTION
**Pull request by ryzokuken**
@jywarren how does this look? Will add some tests for these soon.

### CODE REVIEW

**Comment by jywarren** [comment]
Cool, so would this wait a period before responding, and be able to check if anyone else has replied in that time? Trying to keep in mind not flooding.

**Comment by ryzokuken** [comment]
@jywarren @ananyo2012 @icarito check out this very basic version of the required behavior. Comments and suggestions are welcome.

**Comment by ryzokuken** [comment]
@jywarren This brings us close to finishing this heavily needed behavior. IMO, all that's left is to rectify rests, and we're pretty much done here. Wdyt?

**Comment by jywarren** [comment]
Looks great!

**Comment by ryzokuken** [comment]
@jywarren seems to be a decent increase. This is ready to be merged from my side.

**Comment by ryzokuken** [comment]
@jywarren take a look at this.

**Comment by jywarren** [comment]
This looks super! Thanks, @ryzokuken, looks good to me!

**Pull request merged**
