### PR TITLE
Added Github tag to README

### PR DESCRIPTION
**Pull request by Uarmagan**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@Uarmagan by mistake, you have added the wrong badge (one that belongs to expressjs/express). Please make changes to point the badge to publiclab/plotsbot instead and it would be good to go. Thank you for your contribution.

**Comment by Uarmagan** [comment]
I'll fix it right now, thanks for the help!

**Comment by Uarmagan** [comment]
hope that is correct

**Comment by ryzokuken** [comment]
@Uarmagan this is great, but you harcoded it to a specific value, and it would be required to change this everytime we bump a version. Instead, use this badge: [GitHub tag](https://github.com/publiclab/plotsbot)

Code:

```
[![GitHub tag](https://img.shields.io/github/tag/publiclab/plotsbot.svg)](https://github.com/publiclab/plotsbot)
```

**Comment by Uarmagan** [comment]
Ah, I understand now. Thank You for all your help. if it's not quite correct I can try again. Thank you for being so patient with me.

**Comment by ryzokuken** [comment]
@Uarmagan hey! Sorry for the delay... This looks perfect! Merging this.

**Comment by Uarmagan** [comment]
@ryzokuken Awesome! Thank you for all your help!

**Pull request merged**
