### PR TITLE
Add basic functionality for heat behavior

### PR DESCRIPTION
**Pull request by ryzokuken**
We need to merge #66 first though.

### CODE REVIEW

**Comment by icarito** [comment]
Super!

**Comment by ryzokuken** [comment]
Done with regard to #65

**Comment by ananyo2012** [comment]
This looks good. Once you are done with the tests we can merge this.

**Comment by ryzokuken** [comment]
I cannot find a decent way to test this behaviour, help me.

**Comment by ananyo2012** [comment]
With respect to the promise written in https://github.com/publiclab/plotsbot/pull/66 just make a method that will mock the execution of the process and make the promise reject or resolve.

**Comment by ananyo2012** [comment]
Cleverly done!

**Comment by jywarren** [comment]
This is a really good self-contained example of an entire behavior -- maybe we should link to this from the README as an example of everything you need to add a behavior?

**Comment by ryzokuken** [comment]
@jywarren Sure, I will do that right now.

**Pull request merged**
