### PR TITLE
Add the version behavior (resolves #69)

### LINKED ISSUE #69: About or Introduce behavior
A behavior in which you could ask plotsbot to introduce/identify itself. Mainly, I was interested to ask a plotsbot instance which version it was on.

I think it would be really useful, especially when there are some issues and you want to check the current version to determine if that bug has been fixed already and stuff like that.

@jywarren @ananyo2012 @icarito any thoughts?

### PR DESCRIPTION
**Pull request by ryzokuken**

### CODE REVIEW

**Comment by jywarren** [comment]
Is this ready to merge? If so, please note that in future PRs, thanks! If you're ready, go ahead!

**Comment by ryzokuken** [comment]
@jywarren Now that I have added the tests, it should be more or less complete. Will merge this as soon as we're satisfied with this new behavior.

**Comment by ryzokuken** [comment]
@jywarren merging this.

**Comment by jywarren** [comment]
Super!!

**Pull request merged**
