### PR TITLE
Add support for mini-behaviors and demo it (fixes #95)

### LINKED ISSUE #95: Simple "keyword/response" mini-behaviors
In Slack, the `slackbot` can be configured to respond to a list of keyword triggers in a simple format, where you type the trigger words and then the string that's returned:

* `cat` => `Hi there, a cat is a pet.`
* `file an issue` => `Want to file a GitHub issue? https://github.com/publiclab/plots2/issues/`

It'd be great to be able to add simple behaviors to `plotsbot` by just adding a single line like this to a "keywords" list. What do you think?

### PR DESCRIPTION
**Pull request by ryzokuken**
@jywarren take a look at this as soon as possible, and let's get this merged!

https://github.com/publiclab/plotsbot/compare/mini-behaviors?expand=1#diff-09b0d1ce42aaadb6154c5e9b97d4c743R40 is basically how I decided it should work, simple one-liner, feedback appreciated.

Let me know if it's fine by you, and I'll remove the sample code and everything.

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, this is awesome. Can we add usage to the README along with a link to the line where new ones should be added? 

`new SimpleMessageBehavior('help', 'this is the help text'),` <= this would be the only line needed, right?

And this does not yet support passing a function() as a response, I assume, but that will be awesome too :-)

**Comment by jywarren** [comment]
Do you think we should move the array of these mini behaviors into a JSON file?

**Comment by ryzokuken** [comment]
@jywarren we can, sure. Could we talk for a minute if you were free for a small amount of time today and we could talk this out?

**Comment by jywarren** [comment]
Sorry @ryzokuken -- i'm afraid I don't have time before leaving for New Orleans -- do you think you could jot out your questions here? Thank you!

**Comment by jywarren** [comment]
I apologise, I don't often have time for synchronous chatting, but I will be free in about 20 minutes if you're interested in chatting?

**Comment by jywarren** [comment]
What do you think about the JSON idea? Seems with that addition, this could be merged!

**Comment by ryzokuken** [comment]
On the Matrix chatroom?

**Pull request merged**
