### PR TITLE
Add a CLI interface for testing/experimentation

### PR DESCRIPTION
**Pull request by ryzokuken**

### CODE REVIEW

**Comment by jywarren** [comment]
Would it be possible to add a follow-on issue that makes the CLI interface
accessible in the GitHub pages demo?

**Comment by ryzokuken** [comment]
For that, we'd also need to host an API that a client-side application (the GH pages app) would call. I could definitely add an interface for that too, though. Please feel free to add an issue. Or should I?

**Comment by jywarren** [comment]
please add the issue and the additional steps you mentioned. Thanks!

**Comment by jywarren** [comment]
Oh, this looks great. But perhaps before we start adding too many features, we should get tests set up? But if you'd like to merge this, go ahead.

**Comment by ryzokuken** [comment]
@ananyo2012 @jywarren Added quite a few improvements (4 patches, to be precise). Look into this and tell me what you think about this + if you have any concerns regarding anything in this PR.

Now that I have started to immerse myself in this, we could use modules like https://github.com/chalk/chalk and https://github.com/sindresorhus/ora. Or perhaps all we needed was a minimal interface and I could stash up these in an issue for later?

**Comment by jywarren** [comment]
Yes let's do a minimal first and do changes in separate PRs. Thanks!

**Comment by ryzokuken** [comment]
@ananyo2012 Merge this whenever you're ready.

**Comment by ananyo2012** [comment]
And regarding the CLI let's keep it simple for now. We can think about improvements in it later.

**Pull request merged**
